'use client';

import { FormEvent, useState } from 'react';

const services = [
  { name: 'Traditional Thai Massage', duration: '60 MINUTES', price: 1499, category: 'thai', image: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?auto=format&fit=crop&w=900&q=80', copy: 'Rhythmic stretching and pressure to revive energy and release tension.' },
  { name: 'Aroma Oil Massage', duration: '60 MINUTES', price: 1799, category: 'oil', image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=900&q=80', copy: 'Warm aromatic oils and flowing strokes for complete release.' },
  { name: 'Thai Herbal Massage', duration: '90 MINUTES', price: 2499, category: 'wellness', image: 'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?auto=format&fit=crop&w=900&q=80', copy: 'A warm herbal compress ritual to soothe tired muscles.' },
  { name: "Couple's Retreat", duration: '90 MINUTES', price: 4499, category: 'couples', image: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?auto=format&fit=crop&w=900&q=80', copy: 'A private escape for two, with a shared sense of renewal.' },
];
const categories = [['all', 'All therapies'], ['thai', 'Thai massage'], ['oil', 'Oil massage'], ['couples', 'Couples'], ['wellness', 'Wellness']];

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [filter, setFilter] = useState('all');
  const [service, setService] = useState(services[0].name);
  const [date, setDate] = useState('');
  const [time, setTime] = useState('11:00 AM');
  const [guests, setGuests] = useState('1 Guest');
  const [booking, setBooking] = useState<{ id: string; service: string; date: string; time: string; guests: string; price: number } | null>(null);
  const selected = services.find(item => item.name === service) ?? services[0];
  const bookService = (name: string) => { setService(name); document.querySelector('#booking')?.scrollIntoView({ behavior: 'smooth' }); };
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const formattedDate = new Date(`${date}T12:00:00`).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });
    setBooking({ id: `TS-${Math.floor(100000 + Math.random() * 899999)}`, service, date: formattedDate, time, guests, price: selected.price });
  };
  const closeMenu = () => setMenuOpen(false);
  return <>
    <header className="site-header"><a className="brand" href="#home"><span className="brand-mark">✦</span><span>THAI<br /><em>SPA</em></span></a><nav className={`main-nav ${menuOpen ? 'open' : ''}`} aria-label="Main navigation">{[['#about','About'],['#services','Services'],['#offers','Offers'],['#facilities','Facilities'],['#reviews','Reviews'],['#contact','Contact']].map(([href,label]) => <a key={href} onClick={closeMenu} href={href}>{label}</a>)}</nav><a className="header-cta" href="#booking">Book a ritual <span>↗</span></a><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Open menu">☰</button></header>
    <main>
      <section className="hero" id="home"><div className="hero-copy"><p className="eyebrow light">THAI-INSPIRED WELLNESS</p><h1>Your journey to<br /><i>deep relaxation</i><br />begins here.</h1><p className="hero-text">Experience thoughtful therapies that soften the body, quieten the mind, and return you to yourself.</p><div className="hero-actions"><a className="button gold" href="#booking">Book an appointment <span>→</span></a><a className="text-link" href="#services">Explore therapies <span>↓</span></a></div><div className="hero-trust"><span>✦ Professional therapists</span><span>✦ Premium products</span><span>✦ Peaceful ambience</span></div></div><div className="hero-bottom"><span>SCROLL TO DISCOVER</span><span className="scroll-line" /><span>01 / 07</span></div></section>
      <section className="booking-wrap" id="booking"><div className="booking-intro"><p className="eyebrow">RESERVE YOUR TIME</p><h2>A moment made<br />just for <i>you.</i></h2></div><form className="booking-form" onSubmit={submit}><label>Choose a therapy<select value={service} onChange={e => setService(e.target.value)}>{services.map(item => <option key={item.name} value={item.name}>{item.name} — ₹{item.price.toLocaleString('en-IN')}</option>)}</select></label><label>Preferred date<input type="date" required min={new Date().toISOString().split('T')[0]} value={date} onChange={e => setDate(e.target.value)} /></label><label>Arrival time<select value={time} onChange={e => setTime(e.target.value)}>{['11:00 AM','01:00 PM','03:00 PM','05:00 PM','07:00 PM'].map(slot => <option key={slot}>{slot}</option>)}</select></label><label>Guests<select value={guests} onChange={e => setGuests(e.target.value)}><option>1 Guest</option><option>2 Guests</option></select></label><button className="button dark">Check availability <span>→</span></button></form></section>
      <section className="about section" id="about"><div className="about-image image-card"><img src="https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=85" alt="Serene Thai Spa treatment room" /><span className="image-note">EST. 2018<br /><b>THAI SPA</b></span></div><div className="about-copy"><p className="eyebrow">OUR PHILOSOPHY</p><h2>A sanctuary away<br />from the <i>everyday.</i></h2><p>At Thai Spa, ancient Thai healing traditions meet a modern sense of calm. Every detail — from the botanical oils to the quiet aftercare — is shaped to help you feel deeply restored.</p><p>Our experienced therapists listen carefully, then tailor your ritual around what your body needs most.</p><a className="arrow-link" href="#facilities">Discover our sanctuary <span>→</span></a></div></section>
      <section className="services section" id="services"><div className="section-head"><div><p className="eyebrow">OUR THERAPIES</p><h2>Find your <i>ritual.</i></h2></div><a className="arrow-link" href="#booking">View all therapies <span>→</span></a></div><div className="filters">{categories.map(([key,label]) => <button key={key} className={filter === key ? 'active' : ''} onClick={() => setFilter(key)}>{label}</button>)}</div><div className="service-grid">{services.filter(item => filter === 'all' || item.category === filter).map(item => <article className="service-card" key={item.name}><img src={item.image} alt={item.name} /><div><p className="service-meta">{item.duration}<span>₹{item.price.toLocaleString('en-IN')}</span></p><h3>{item.name}</h3><p>{item.copy}</p><button className="book-service" onClick={() => bookService(item.name)}>Reserve this ritual →</button></div></article>)}</div></section>
      <section className="experience"><div className="experience-copy"><p className="eyebrow light">THE THAI SPA EXPERIENCE</p><h2>Leave feeling<br /><i>lighter than air.</i></h2></div><div className="steps">{[['01','Arrive','Leave the outside world at the door.'],['02','Relax','Let expert hands take care of you.'],['03','Rejuvenate','Step out refreshed and renewed.']].map(([number,title,copy]) => <div key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></div>)}</div></section>
      <section className="offers section" id="offers"><p className="eyebrow center">A LITTLE EXTRA CALM</p><h2 className="center">Relax more. <i>Save more.</i></h2><div className="offer-grid">{[['FIRST VISIT OFFER','20%','For your first moment of self-care with us.','FIRST20'],['WEEKDAY WELLNESS','25%','Monday to Thursday · 11 AM to 4 PM','WEEKDAY25'],["COUPLE'S ESCAPE",'15%','On any qualifying shared spa experience.','COUPLE15']].map(([title,discount,copy,code],index) => <article key={code} className={index === 1 ? 'featured' : ''}><p>{title}</p><strong>{discount} <em>OFF</em></strong><span>{copy}</span><button className="claim-offer" onClick={() => { alert(`Offer ${code} will be applied when you confirm your appointment.`); document.querySelector('#booking')?.scrollIntoView({ behavior: 'smooth' }); }}>{index === 0 ? 'Claim offer' : 'Reserve now'} →</button></article>)}</div></section>
      <section className="facilities section" id="facilities"><div className="section-head"><div><p className="eyebrow">OUR SPACE</p><h2>Made for <i>unwinding.</i></h2></div><p className="facilities-note">Every element of Thai Spa has been considered for your comfort and care. Facilities may vary by location.</p></div><div className="facility-grid"><div className="facility-tall"><img src="https://images.unsplash.com/photo-1560750588-73207b1ef5b8?auto=format&fit=crop&w=1000&q=80" alt="Spa relaxation lounge" /><p>Quiet relaxation lounge</p></div><div className="facility-list">{['Private treatment rooms','Luxury couples suites','Herbal tea ritual','Premium essential oils','Fresh linens & robes','Easy on-site parking'].map(item => <span key={item}>{item}</span>)}</div><div className="facility-small"><img src="https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1000&q=80" alt="Calm spa details" /><p>Botanical care, everywhere</p></div></div></section>
      <section className="reviews section" id="reviews"><div className="rating"><span>4.9</span><div>★★★★★<small>BASED ON 500+ GUEST REVIEWS</small></div></div><blockquote>“Beautiful ambience and an incredibly relaxing experience. My therapist was attentive from the first minute to the last.”<footer>— PRIYA M., VERIFIED GUEST</footer></blockquote></section>
      <section className="contact" id="contact"><div><p className="eyebrow light">A MOMENT OF CALM AWAITS</p><h2>Ready to feel<br /><i>like yourself again?</i></h2><a className="button gold" href="#booking">Book an appointment <span>→</span></a></div><div className="contact-details"><p><b>VISIT US</b><br />123 Wellness Lane, Your City<br />India 000000</p><p><b>OPEN DAILY</b><br />10:00 AM — 10:00 PM<br /><span className="open">● OPEN NOW</span></p><p><b>SPEAK WITH US</b><br /><a href="tel:+910000000000">+91 00000 00000</a><br /><a href="mailto:hello@thaispa.in">hello@thaispa.in</a></p></div></section>
    </main>
    <footer><a className="brand" href="#home"><span className="brand-mark">✦</span><span>THAI<br /><em>SPA</em></span></a><p>Relax. Rejuvenate. Rediscover Yourself.</p><span>© 2026 Thai Spa. All rights reserved.</span></footer><a className="whatsapp" target="_blank" rel="noreferrer" href="https://wa.me/910000000000?text=Hi%2C%20I%20would%20like%20to%20book%20an%20appointment%20at%20Thai%20Spa.%20Please%20help%20me%20with%20available%20slots." aria-label="Book on WhatsApp">◔</a>
    {booking && <div className="modal show" role="dialog" aria-modal="true"><div className="modal-card"><button className="close-modal" onClick={() => setBooking(null)} aria-label="Close confirmation">×</button><span className="confirmation-icon">✓</span><p className="eyebrow">AVAILABILITY CONFIRMED</p><h2>Your ritual is<br /><i>reserved.</i></h2><div className="confirmation-details"><strong>{booking.service}</strong><br />{booking.date} · {booking.time}<br />{booking.guests} · <strong>₹{booking.price.toLocaleString('en-IN')}</strong><br /><small>Booking ID: {booking.id}</small></div><a className="button dark" target="_blank" rel="noreferrer" href={`https://wa.me/910000000000?text=${encodeURIComponent(`Hi Thai Spa, I would like to confirm booking ${booking.id}: ${booking.service} on ${booking.date} at ${booking.time}.`)}`}>Confirm on WhatsApp <span>→</span></a></div></div>}
  </>;
}
